:--> 2023-08-16 15:10:25,454 INFO Bot srarted
:--> 2023-08-16 15:10:25,454 INFO Start polling.
:--> 2023-08-16 15:10:31,123 INFO 354585871 (Дмитрий) --> Вошел в чат
:--> 2023-08-16 15:12:32,455 WARNING Polling is stopped.
:--> 2023-08-16 15:12:32,470 INFO Stop polling...
:--> 2023-08-16 15:12:33,509 INFO Bot srarted
:--> 2023-08-16 15:12:33,509 INFO Start polling.
:--> 2023-08-16 15:12:35,215 INFO 354585871 (Дмитрий) --> Вошел в чат
:--> 2023-08-16 15:12:36,427 INFO Неизвестное сообщение: {"message_id": 8, "from": {"id": 354585871, "is_bot": false, "first_name": "Дмитрий", "username": "DmKusov", "language_code": "ru"}, "chat": {"id": 354585871, "first_name": "Дмитрий", "username": "DmKusov", "type": "private"}, "date": 1692187956, "text": "🤠Посмотреть фотографии"}
:--> 2023-08-16 15:20:21,461 WARNING Polling is stopped.
:--> 2023-08-16 15:20:21,477 INFO Stop polling...
:--> 2023-08-16 15:20:22,927 INFO Bot srarted
:--> 2023-08-16 15:20:22,927 INFO Start polling.
:--> 2023-08-16 15:20:24,937 INFO Неизвестное сообщение: {"message_id": 11, "from": {"id": 354585871, "is_bot": false, "first_name": "Дмитрий", "username": "DmKusov", "language_code": "ru"}, "chat": {"id": 354585871, "first_name": "Дмитрий", "username": "DmKusov", "type": "private"}, "date": 1692188424, "text": "🤠Посмотреть фотографии"}
:--> 2023-08-16 15:20:40,279 WARNING Polling is stopped.
:--> 2023-08-16 15:20:40,295 INFO Stop polling...
:--> 2023-08-16 15:20:41,236 INFO Bot srarted
:--> 2023-08-16 15:20:41,236 INFO Start polling.
:--> 2023-08-16 15:20:43,782 INFO Неизвестное сообщение: {"message_id": 14, "from": {"id": 354585871, "is_bot": false, "first_name": "Дмитрий", "username": "DmKusov", "language_code": "ru"}, "chat": {"id": 354585871, "first_name": "Дмитрий", "username": "DmKusov", "type": "private"}, "date": 1692188443, "text": "🤠Посмотреть фотографии"}
:--> 2023-08-16 15:21:04,095 WARNING Polling is stopped.
:--> 2023-08-16 15:21:04,110 INFO Stop polling...
:--> 2023-08-16 15:21:05,345 INFO Bot srarted
:--> 2023-08-16 15:21:05,346 INFO Start polling.
:--> 2023-08-16 15:22:45,699 WARNING Polling is stopped.
:--> 2023-08-16 15:22:45,715 INFO Stop polling...
:--> 2023-08-16 15:22:46,748 INFO Bot srarted
:--> 2023-08-16 15:22:46,748 INFO Start polling.
:--> 2023-08-16 15:22:48,327 ERROR Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse reply keyboard markup json object")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/photo_nandlers.py", line 11, in get_first_photo
    await message.answer('Вот он я', reply_markup=get_inline_photo)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse reply keyboard markup json object
:--> 2023-08-16 15:29:13,556 WARNING Polling is stopped.
:--> 2023-08-16 15:29:13,574 INFO Stop polling...
:--> 2023-08-16 15:29:14,645 INFO Bot srarted
:--> 2023-08-16 15:29:14,645 INFO Start polling.
:--> 2023-08-16 15:30:17,674 WARNING Polling is stopped.
:--> 2023-08-16 15:30:17,689 INFO Stop polling...
:--> 2023-08-16 15:30:18,866 INFO Bot srarted
:--> 2023-08-16 15:30:18,866 INFO Start polling.
:--> 2023-08-16 15:30:20,168 ERROR Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse reply keyboard markup json object")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/photo_nandlers.py", line 11, in get_first_photo
    await message.answer('Вот он я', reply_markup=get_inline_photo)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse reply keyboard markup json object
:--> 2023-08-16 15:30:22,828 ERROR Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse reply keyboard markup json object")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/photo_nandlers.py", line 11, in get_first_photo
    await message.answer('Вот он я', reply_markup=get_inline_photo)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse reply keyboard markup json object
:--> 2023-08-16 15:31:15,120 WARNING Polling is stopped.
:--> 2023-08-16 15:31:15,136 INFO Stop polling...
:--> 2023-08-16 15:31:16,205 INFO Bot srarted
:--> 2023-08-16 15:31:16,205 INFO Start polling.
:--> 2023-08-16 15:31:18,218 ERROR Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse reply keyboard markup json object")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/photo_nandlers.py", line 11, in get_first_photo
    await message.answer(text='Вот он я', reply_markup=get_inline_photo)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse reply keyboard markup json object
:--> 2023-08-16 15:31:34,176 WARNING Polling is stopped.
:--> 2023-08-16 15:31:34,191 INFO Stop polling...
:--> 2023-08-16 15:31:35,259 INFO Bot srarted
:--> 2023-08-16 15:31:35,259 INFO Start polling.
:--> 2023-08-16 15:32:52,878 WARNING Polling is stopped.
:--> 2023-08-16 15:32:52,893 INFO Stop polling...
:--> 2023-08-16 15:32:54,362 INFO Bot srarted
:--> 2023-08-16 15:32:54,362 INFO Start polling.
:--> 2023-08-16 15:54:45,160 INFO Неизвестное сообщение: {"message_id": 34, "from": {"id": 354585871, "is_bot": false, "first_name": "Дмитрий", "username": "DmKusov", "language_code": "ru"}, "chat": {"id": 354585871, "first_name": "Дмитрий", "username": "DmKusov", "type": "private"}, "date": 1692190485, "photo": [{"file_id": "AgACAgIAAxkBAAMiZNzHFcgAAccSRbaiQ-_w-Avdi7OfAAImzjEblIToSjDOORcBEZBlAQADAgADcwADMAQ", "file_unique_id": "AQADJs4xG5SE6Ep4", "file_size": 1139, "width": 67, "height": 90}, {"file_id": "AgACAgIAAxkBAAMiZNzHFcgAAccSRbaiQ-_w-Avdi7OfAAImzjEblIToSjDOORcBEZBlAQADAgADbQADMAQ", "file_unique_id": "AQADJs4xG5SE6Epy", "file_size": 10695, "width": 240, "height": 320}, {"file_id": "AgACAgIAAxkBAAMiZNzHFcgAAccSRbaiQ-_w-Avdi7OfAAImzjEblIToSjDOORcBEZBlAQADAgADeAADMAQ", "file_unique_id": "AQADJs4xG5SE6Ep9", "file_size": 44197, "width": 600, "height": 800}, {"file_id": "AgACAgIAAxkBAAMiZNzHFcgAAccSRbaiQ-_w-Avdi7OfAAImzjEblIToSjDOORcBEZBlAQADAgADeQADMAQ", "file_unique_id": "AQADJs4xG5SE6Ep-", "file_size": 56599, "width": 960, "height": 1280}]}
:--> 2023-08-16 15:55:28,863 WARNING Polling is stopped.
:--> 2023-08-16 15:55:28,884 INFO Stop polling...
:--> 2023-08-16 15:55:30,307 INFO Bot srarted
:--> 2023-08-16 15:55:30,307 INFO Start polling.
:--> 2023-08-16 15:57:23,819 INFO Неизвестное сообщение: {"message_id": 40, "from": {"id": 354585871, "is_bot": false, "first_name": "Дмитрий", "username": "DmKusov", "language_code": "ru"}, "chat": {"id": 354585871, "first_name": "Дмитрий", "username": "DmKusov", "type": "private"}, "date": 1692190643, "photo": [{"file_id": "AgACAgIAAxkBAAMoZNzHs3OEo3YD0LWyDa4QG6AIDyUAAifOMRuUhOhKYtodHn1dtJQBAAMCAANzAAMwBA", "file_unique_id": "AQADJ84xG5SE6Ep4", "file_size": 1838, "width": 80, "height": 90}, {"file_id": "AgACAgIAAxkBAAMoZNzHs3OEo3YD0LWyDa4QG6AIDyUAAifOMRuUhOhKYtodHn1dtJQBAAMCAANtAAMwBA", "file_unique_id": "AQADJ84xG5SE6Epy", "file_size": 28937, "width": 283, "height": 320}, {"file_id": "AgACAgIAAxkBAAMoZNzHs3OEo3YD0LWyDa4QG6AIDyUAAifOMRuUhOhKYtodHn1dtJQBAAMCAAN4AAMwBA", "file_unique_id": "AQADJ84xG5SE6Ep9", "file_size": 42971, "width": 426, "height": 481}]}
:--> 2023-08-16 15:58:36,321 WARNING Polling is stopped.
:--> 2023-08-16 15:58:36,337 INFO Stop polling...
:--> 2023-08-16 15:58:37,643 INFO Bot srarted
:--> 2023-08-16 15:58:37,643 INFO Start polling.
:--> 2023-08-16 16:00:55,086 WARNING Polling is stopped.
:--> 2023-08-16 16:00:55,102 INFO Stop polling...
:--> 2023-08-16 16:00:56,436 INFO Bot srarted
:--> 2023-08-16 16:00:56,437 INFO Start polling.
:--> 2023-08-16 16:01:27,275 WARNING Polling is stopped.
:--> 2023-08-16 16:01:27,290 INFO Stop polling...
:--> 2023-08-16 16:01:28,317 INFO Bot srarted
:--> 2023-08-16 16:01:28,318 INFO Start polling.
:--> 2023-08-16 16:01:32,777 INFO 354585871 (Дмитрий) --> Вошел в чат
:--> 2023-08-16 18:16:02,315 ERROR Cause exception while getting updates.
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
:--> 2023-08-16 22:13:43,868 ERROR Cause exception while getting updates.
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
:--> 2023-08-17 10:03:27,527 ERROR Cause exception while getting updates.
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
:--> 2023-08-17 10:57:32,672 ERROR Cause exception while getting updates.
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
:--> 2023-08-17 16:08:57,099 WARNING Polling is stopped.
:--> 2023-08-17 16:08:57,165 INFO Stop polling...
:--> 2023-08-17 16:08:58,280 INFO Bot srarted
:--> 2023-08-17 16:08:58,281 INFO Start polling.
:--> 2023-08-17 16:15:07,211 WARNING Polling is stopped.
:--> 2023-08-17 16:15:07,234 INFO Stop polling...
:--> 2023-08-17 16:15:08,368 INFO Bot srarted
:--> 2023-08-17 16:15:08,368 INFO Start polling.
:--> 2023-08-17 16:15:54,274 WARNING Polling is stopped.
:--> 2023-08-17 16:15:54,290 INFO Stop polling...
:--> 2023-08-17 16:15:55,223 INFO Bot srarted
:--> 2023-08-17 16:15:55,223 INFO Start polling.
:--> 2023-08-17 16:15:58,656 INFO 354585871 (Дмитрий) --> Вошел в чат
:--> 2023-08-17 16:16:00,151 ERROR Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=BadRequest("Can't parse reply keyboard markup json object")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/voices_handlers.py", line 8, in my_voice
    await message.answer('Какой воис вы хотите послушать?',
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 413, in answer
    return await self.bot.send_message(
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse reply keyboard markup json object
:--> 2023-08-17 16:16:12,261 WARNING Polling is stopped.
:--> 2023-08-17 16:16:12,277 INFO Stop polling...
:--> 2023-08-17 16:16:14,189 INFO Bot srarted
:--> 2023-08-17 16:16:14,190 INFO Start polling.
:--> 2023-08-17 16:16:15,731 INFO 354585871 (Дмитрий) --> Вошел в чат
:--> 2023-08-17 16:18:39,905 WARNING Polling is stopped.
:--> 2023-08-17 16:18:39,925 INFO Stop polling...
:--> 2023-08-17 16:18:41,139 INFO Bot srarted
:--> 2023-08-17 16:18:41,140 INFO Start polling.
:--> 2023-08-17 16:18:42,480 ERROR Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("module 'email.message' has no attribute 'answer'")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/voices_handlers.py", line 14, in gpt_answer
    await message.answer('voice')
AttributeError: module 'email.message' has no attribute 'answer'
:--> 2023-08-17 16:19:18,384 INFO 354585871 (Дмитрий) --> Вошел в чат
:--> 2023-08-17 16:19:21,290 ERROR Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("module 'email.message' has no attribute 'answer'")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/voices_handlers.py", line 14, in gpt_answer
    await message.answer('voice')
AttributeError: module 'email.message' has no attribute 'answer'
:--> 2023-08-17 16:19:28,639 ERROR Task exception was never retrieved
future: <Task finished name='Task-22' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("module 'email.message' has no attribute 'answer'")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/voices_handlers.py", line 18, in gpt_answer
    await message.answer('voice')
AttributeError: module 'email.message' has no attribute 'answer'
:--> 2023-08-17 16:19:29,328 ERROR Task exception was never retrieved
future: <Task finished name='Task-25' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=AttributeError("module 'email.message' has no attribute 'answer'")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/voices_handlers.py", line 22, in gpt_answer
    await message.answer('voice')
AttributeError: module 'email.message' has no attribute 'answer'
:--> 2023-08-17 16:19:52,728 WARNING Polling is stopped.
:--> 2023-08-17 16:19:52,745 INFO Stop polling...
:--> 2023-08-17 16:20:08,359 INFO Bot srarted
:--> 2023-08-17 16:20:08,360 INFO Start polling.
:--> 2023-08-17 16:39:53,453 INFO Неизвестное сообщение: {"message_id": 76, "from": {"id": 354585871, "is_bot": false, "first_name": "Дмитрий", "username": "DmKusov", "language_code": "ru"}, "chat": {"id": 354585871, "first_name": "Дмитрий", "username": "DmKusov", "type": "private"}, "date": 1692279593, "voice": {"duration": 82, "mime_type": "audio/ogg", "file_id": "AwACAgIAAxkBAANMZN4jKfrrojByHBBNaQT5Ayq4z_0AAt81AALYmPlKSmKNZn2zP8swBA", "file_unique_id": "AgAD3zUAAtiY-Uo", "file_size": 325857}}
:--> 2023-08-17 16:42:41,140 INFO Неизвестное сообщение: {"message_id": 78, "from": {"id": 354585871, "is_bot": false, "first_name": "Дмитрий", "username": "DmKusov", "language_code": "ru"}, "chat": {"id": 354585871, "first_name": "Дмитрий", "username": "DmKusov", "type": "private"}, "date": 1692279761, "voice": {"duration": 53, "mime_type": "audio/ogg", "file_id": "AwACAgIAAxkBAANOZN4j0RGmHikW7k7QMbuHhwgMIY8AAu41AALYmPlKrcxK8GWzn38wBA", "file_unique_id": "AgAD7jUAAtiY-Uo", "file_size": 210671}}
:--> 2023-08-17 16:43:18,389 INFO Неизвестное сообщение: {"message_id": 81, "from": {"id": 354585871, "is_bot": false, "first_name": "Дмитрий", "username": "DmKusov", "language_code": "ru"}, "chat": {"id": 354585871, "first_name": "Дмитрий", "username": "DmKusov", "type": "private"}, "date": 1692279798, "voice": {"duration": 74, "mime_type": "audio/ogg", "file_id": "AwACAgIAAxkBAANRZN4j9hir_BC_rMhm0pAm30OHe0oAAvQ1AALYmPlKabF_AAG7ZMChMAQ", "file_unique_id": "AgAD9DUAAtiY-Uo", "file_size": 289059}}
:--> 2023-08-17 16:43:30,242 WARNING Polling is stopped.
:--> 2023-08-17 16:43:30,265 INFO Stop polling...
:--> 2023-08-17 16:43:31,365 INFO Bot srarted
:--> 2023-08-17 16:43:31,366 INFO Start polling.
:--> 2023-08-17 16:44:20,787 WARNING Polling is stopped.
:--> 2023-08-17 16:44:20,803 INFO Stop polling...
:--> 2023-08-17 16:44:22,057 INFO Bot srarted
:--> 2023-08-17 16:44:22,058 INFO Start polling.
:--> 2023-08-17 16:44:33,197 ERROR Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=TypeError("object method can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/dmitriykyc/PythonProjects/Yandex_Kusov/handlers/photo_nandlers.py", line 17, in choose_task
    await call.answer
TypeError: object method can't be used in 'await' expression
:--> 2023-08-17 16:44:44,283 WARNING Polling is stopped.
:--> 2023-08-17 16:44:44,299 INFO Stop polling...
:--> 2023-08-17 16:44:45,523 INFO Bot srarted
:--> 2023-08-17 16:44:45,523 INFO Start polling.
:--> 2023-08-17 17:21:36,104 WARNING Polling is stopped.
:--> 2023-08-17 17:21:36,142 INFO Stop polling...
